calibrated: 1
equilibrium:
    sign: -1
    signFlexor: 1
    signExtensor: -1
    nameFlexor: "left_horizontal_abductor"
    nameExtensor: "left_horizontal_adductor"
    servoRange: 12.5664
    servoOffset: 0.9
    loadLimit: 0.5  # Testing limitLoad method in equilibrium_model.py.
signEncoder: 1
signJoint: 1
name: "left_shoulder_yaw"
nameEncoder: "left_shoulder_yaw_encoder"
minAngle: -0.79
maxAngle: 1.04
maxAbsForwardError: 0.25
gains:
    P: 0.015
    I: 0.00002
    D: 0.1
