controller_list:
  - name: gummi_left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - left_shoulder_yaw
      - left_shoulder_roll
      - left_shoulder_pitch
      - left_upperarm_roll
      - left_elbow
      - forearm_roll
      - wrist_pitch
  # - name: fake_left_gripper_controller
    # joints:
      # - gripper
